Add notebook example for local experiment
savvihub/examples pull request #1
Opened 2021-11-05 14:48 UTC by hippothewild

Local experiment 기능을 이용해 vessl을 사용해볼 수 있는 가벼운 example notebook입니다.

2021-11-08 00:59 UTC, chandescartes requested changes

2021-11-08 00:59 UTC, chandescartes commented on vessl-intro.ipynb
> +    "[Vessl](https://vessl.ai) is a machine learning platform that allows researchers to train and monitor models in scale as a team. In this notebook you'll see how you can integrate local ML experi
```suggestion
    "[Vessl](https://vessl.ai) is a machine learning platform that allows researchers to train and monitor models in scale as a team. In this notebook, you'll see how you can integrate local ML experiments with Vessl to empower your research workflow. For more detailed information, check out our [docs](https://docs.vessl.ai/)!"
```

2021-11-08 00:59 UTC, chandescartes commented on vessl-intro.ipynb
> +    "Let's install Vessl SDK and required libraries first. If you're running this Jupyter Notebook on Vessl workspace, most of the required libraries should already be installed including the SDK. Ex
```suggestion
    "Let's install the Vessl SDK and required libraries first. If you're running this Jupyter Notebook on a Vessl workspace, most of these should already be installed. Examples in this Notebook run well on Vessl SDK versions 0.1.15 or higher."
```

2021-11-08 00:59 UTC, chandescartes commented on vessl-intro.ipynb
> +    "# Use CLI to sign in into Vessl and configure default organization and project\n",
```suggestion
    "# Use the CLI to sign in into Vessl and configure a default organization and project\n",
```

2021-11-08 00:59 UTC, chandescartes commented on vessl-intro.ipynb
> +    "vessl.configure(organization_name=\"vessl\", project_name=\"examples\")"
(vessl.configure 전에 import vessl 줄 추가해야 에러가 안뜹니다)

2021-11-08 00:59 UTC, chandescartes commented on vessl-intro.ipynb
> +    "# You can also programatically set default organization and project using Python API\n",
```suggestion
    "# You can also programatically set a default organization and project using the Python API\n",
```

2021-11-08 00:59 UTC, chandescartes commented on vessl-intro.ipynb
> +    "### 1. Install Vessl SDK and Required Libraries\n",
```suggestion
    "### 1. Install Vessl SDK and required libraries\n",
```

2021-11-08 00:59 UTC, chandescartes commented on vessl-intro.ipynb
> +    "### 2. Prepare Model Code and Dataset\n",
```suggestion
    "### 2. Prepare model code and dataset\n",
```

2021-11-08 00:59 UTC, chandescartes commented on vessl-intro.ipynb
> +    "In this example, we will make a image classification model classifying numeric digits(0-9) using simple 2D CNN and [MNIST](https://paperswithcode.com/dataset/mnist) dataset. We used publicly ava
```suggestion
    "In this example, we will train an image classification model classifying numeric digits (0-9) using a simple 2D CNN and the [MNIST](https://paperswithcode.com/dataset/mnist) dataset. We used a publicly available dataset from torchvision for this example, but you can also import you own datasets using the [Dataset](https://docs.vessl.ai/user-guide/dataset) feature in Vessl!\n",
```

2021-11-08 00:59 UTC, chandescartes commented on vessl-intro.ipynb
> +    "* For more information about the Dataset, please check out ['Dataset' section on docs](https://docs.vessl.ai/user-guide/dataset)."
Remove?

2021-11-08 00:59 UTC, chandescartes commented on vessl-intro.ipynb
> +    "# Define data loader\n",
\n 추가해주세요

2021-11-08 00:59 UTC, chandescartes commented on vessl-intro.ipynb
> +    "### 3. Use vessl.log() to Record Model Training and Test Steps\n",
```suggestion
    "### 3. Use vessl.log() to record model training and test steps\n",
```

2021-11-08 00:59 UTC, chandescartes commented on vessl-intro.ipynb
> +    "### 1. Install Vessl SDK and Required Libraries\n",
첫단어만 소문자가 더 자연스러운거 같습니다

2021-11-08 00:59 UTC, chandescartes commented on vessl-intro.ipynb
> +    "When the model code is ready, the next step is to write a script for training and testing the model. In Vessl, you can record outputs from your training such as metrics, logs and inferences. You
```suggestion
    "When the model code is ready, the next step is to write a script for training and testing the model. With Vessl, you can record outputs from your training such as metrics, logs, and inferences. You can always view the results, compare with other experiments, and save the best one as a model on our Experiment Tracking page. The only thing you need to do is add vessl.log() in your training code!\n",
```

2021-11-08 00:59 UTC, chandescartes commented on vessl-intro.ipynb
> +    "* For detailed information about vessl.log(), Please see [SDK section](https://docs.vessl.ai/api-reference/python-sdk/vessl.log) on the docs.\n",
```suggestion
    "* For more information about vessl.log(), check out our [Python SDK docs](https://docs.vessl.ai/api-reference/python-sdk/vessl.log).\n",
```

2021-11-08 00:59 UTC, chandescartes commented on vessl-intro.ipynb
> +    "* For detailed information about experiment tracking, Please see [공식 문서의 Experiment 항목](https://docs.vessl.ai/user-guide/experiment) on the docs."
```suggestion
    "* For more information on experiment tracking, check out our [experiment docs](https://docs.vessl.ai/user-guide/experiment)."
```

2021-11-08 00:59 UTC, chandescartes commented on vessl-intro.ipynb
> +    "Let's execute the actual experiment! You can create a new experiment by calling vessl.init() and Vessl SDK will record the metrics and logs into the newly created experiment. After the experimen
```suggestion
    "Let's execute the actual experiment! You can create a new experiment by calling vessl.init() and our SDK will record all metrics and logs onto the newly created experiment. After the experiment is finished, you can call vessl.finish() to mark experiment as completed. We automatically call vessl.finish() when your script exits so the last step is optional."
```

2021-11-08 00:59 UTC, chandescartes commented on vessl-intro.ipynb
> +    "Vessl also supports tons of other handy features empowering your machine learning research workflow! For instance:\n",
```suggestion
    "Vessl supports many other features that will improve your machine learning research workflow! For instance:\n",
```

2021-11-08 00:59 UTC, chandescartes commented on vessl-intro.ipynb
> +    "- You can also execute your training job on top of Vessl-managed cluster to run the experiments asynchronously and focus on other important things. See [Creating an Experiment](https://docs.vess
```suggestion
    "- You can also execute your training job on top of Vessl-managed clusters to run the experiments asynchronously and focus on other important things. See [Creating an Experiment](https://docs.vessl.ai/user-guide/experiment/creating-an-experiment) for more information.\n",
```

2021-11-08 00:59 UTC, chandescartes commented on vessl-intro.ipynb
> +    "- Vessl supports distributed experiment for the training that needs huge amount of computing resources - See [Distributed Experiment](https://docs.vessl.ai/user-guide/experiment/distributed-expe
```suggestion
    "- Vessl supports distributed experiments for training that needs large amounts of computing resources - See [Distributed Experiment](https://docs.vessl.ai/user-guide/experiment/distributed-experiment) for more information.\n",
```

2021-11-08 00:59 UTC, chandescartes commented on vessl-intro.ipynb
> +    "- Hyperparameter Optimzation can also be done easily with Vessl! See [Sweep](https://docs.vessl.ai/user-guide/sweep) for more information.\n",
```suggestion
    "- Hyperparameter optimzation can also be done easily with Vessl! See [Sweep](https://docs.vessl.ai/user-guide/sweep) for more information.\n",
```

2021-11-08 00:59 UTC, chandescartes commented on vessl-intro.ipynb
> +    "Maximize your productivity for machine learning research with Vessl - Please also consider [joining our community Slack](https://join.slack.com/t/vessl-ai-community/shared_invite/zt-w7phk2pj-XwG
```suggestion
    "Maximize your research productivity with Vessl - Join our [Slack community](https://join.slack.com/t/vessl-ai-community/shared_invite/zt-w7phk2pj-XwGK42BchBv5qeXYH42iNQ) to chat with other ML researchers, ask questions, provide feedback, or share best practices. Thank you very much!"
```

2021-11-08 04:40 UTC, hippothewild commented
@chandescartes 리뷰 전부 반영했습니다.

2021-11-09 01:11 UTC, chandescartes approved these changes
🥧

2021-11-09 07:43 UTC, merged